// <auto-generated />
namespace GameWatcher.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Howard : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Howard));
        
        string IMigrationMetadata.Id
        {
            get { return "201503222153408_Howard"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
