// <auto-generated />
namespace GameWatcher.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class _26mar2015 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_26mar2015));
        
        string IMigrationMetadata.Id
        {
            get { return "201503260821318_26mar2015"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
